<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'Netresearch\\HttpGuard\\' => array($typo3InstallDir . 'typo3conf/ext/nr_http_guard/Classes/HttpGuard'),
    'Netresearch\\NrHttpGuard\\' => array($typo3InstallDir . 'typo3conf/ext/nr_http_guard/Classes'),
);
